server:
  port: 8081
spring:
  application:
    name: Order

  kafka:
    producer:
      bootstrap-servers: kafka:9093
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer