server:
  port: 8082
spring:
  application:
    name: Payment



  kafka:
    producer:
      bootstrap-servers: kafka:9093

    consumer:
      bootstrap-servers: kafka:9093
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer